phrase:
  project_id: 34465c0ef579396436c48d4643219daf
  push:
    sources:
    - file: ./Files/MultilingualResources/Files.<locale_code>.xlf
      params:
        file_format: "xlf"
        update_translations: true
  pull:
    targets:
    - file: ./Files/MultilingualResources/Files.<locale_code>.xlf
      params:
        file_format: "xlf"
        format_options:
          include_translation_state: true
