phrase:
  project_id: 34465c0ef579396436c48d4643219daf
  push:
    sources:
    - file: ./Files/Strings/en-US/Resources.resw
      params:
        file_format: "windows8_resource"
  pull:
    targets:
    - file: ./Files/MultilingualResources/Files.<locale_code>.xlf
      params:
        file_format: "xlf"
